swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    transport : smtp
    host: 173.194.65.108
    port: 465
    auth_mode: login
    username: biblioatlantide@gmail.com
    password: biblioatlantide2601
    encryption: tls
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
